---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./definitions/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: kyverno
  validation: client

