---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: apps
spec:
  healthChecks:
  - kind: Deployment
    name: podinfo
    namespace: apps
  interval: 5m0s
  path: ./kustomize
  prune: true
  serviceAccountName: dev-team
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: apps
  timeout: 2m0s
  validation: client

